// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiHpzdlCbH8Aup3Ht8d0Hjb_2xGGjsJSs',
    appId: '1:243215214664:web:9e4d1a158d857de637107d',
    messagingSenderId: '243215214664',
    projectId: 'leave-management-e6eba',
    authDomain: 'leave-management-e6eba.firebaseapp.com',
    storageBucket: 'leave-management-e6eba.firebasestorage.app',
    measurementId: 'G-T8WWXY6YKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTk3xfeZwIzTGmbaV3NPpNhYzAWYtkcbQ',
    appId: '1:243215214664:android:56edbe9f1588dc4037107d',
    messagingSenderId: '243215214664',
    projectId: 'leave-management-e6eba',
    storageBucket: 'leave-management-e6eba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD10kxXuKP1t_oWGSjdUHSKXV6Xsfk_xrw',
    appId: '1:243215214664:ios:5b7b888a6b06b2bb37107d',
    messagingSenderId: '243215214664',
    projectId: 'leave-management-e6eba',
    storageBucket: 'leave-management-e6eba.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD10kxXuKP1t_oWGSjdUHSKXV6Xsfk_xrw',
    appId: '1:243215214664:ios:5b7b888a6b06b2bb37107d',
    messagingSenderId: '243215214664',
    projectId: 'leave-management-e6eba',
    storageBucket: 'leave-management-e6eba.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiHpzdlCbH8Aup3Ht8d0Hjb_2xGGjsJSs',
    appId: '1:243215214664:web:d9a7e7b3ce99a95c37107d',
    messagingSenderId: '243215214664',
    projectId: 'leave-management-e6eba',
    authDomain: 'leave-management-e6eba.firebaseapp.com',
    storageBucket: 'leave-management-e6eba.firebasestorage.app',
    measurementId: 'G-392TF0GVM2',
  );
}
